modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Trample%20Everything"
logoFile="icon.png"

[[mods]]
modId="trampleeverything"
version="3.4"
displayName="Trample Everything"
displayURL="https://serilum.com/mod/trample-everything"
authors="Rick South"
description='''A highly configurable mod which makes players trample everything, not just crops.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, BirdieMiner, Cherriesaurus, Jeremy Langford, Michael W. S., Rare Students, Shana Gitnick, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.trampleeverything]]
    modId="collective"
    mandatory=true
    versionRange="[7.61,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.trampleeverything]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21]"
    ordering="NONE"
    side="BOTH"
